title: Nakia  Grier # your name (or website title) here
logo: "/images/kia.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Healthcare worker turned Data analyst <br><br>
    self proclaimed connoisseur of music and baked goods.<br>
    I love using data to explore the differences and similaraties of all the people in the world. <br>
    Seeking my first role as a Data Analyst
    <br><br>
  <a href="https://www.linkedin.com/in/nakia-grier/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
